// Kropsregioner: hvad sker der, tegn, og førstehjælp efter MARCH.
// Indholdet er undervisningsmateriale baseret på TCCC-principper og skal fagligt valideres.

export const MARCH = {
  M: { label: 'M – Massiv blødning', order: 1 },
  A: { label: 'A – Luftvej', order: 2 },
  R: { label: 'R – Respiration', order: 3 },
  C: { label: 'C – Cirkulation', order: 4 },
  H: { label: 'H – Hoved / Hypotermi', order: 5 },
};

export const REGIONS = {
  ekstremitet_ben: {
    name: 'Lår',
    type: 'Ekstremitet',
    march: 'M',
    urgency: 'Kritisk – minutter',
    what: 'Fragmenter kan ramme a. femoralis. En arteriel blødning fra låret kan være livstruende på få minutter. Store fragmenter kan give knusningsskader eller traumatisk amputation.',
    signs: ['Pulserende eller vedvarende kraftig blødning', 'Blod der hurtigt gennemvæder tøjet eller samler sig under personen', 'Bleghed, uro, hurtig puls (begyndende shock)'],
    aid: [
      'Tourniquet højt og stramt på låret (under beskydning/trussel: "high and tight")',
      'Stram til blødningen stopper og distal puls forsvinder – smerte er forventet',
      'Notér tidspunkt på tourniquet / patient',
      'Når situationen tillader: revurdér, og flyt evt. til 5–8 cm over såret med ny tourniquet',
      'Ved utilstrækkelig effekt: tourniquet nr. 2 lige over den første',
    ],
    gear: ['tourniquet', 'trykforbinding', 'markor'],
  },
  ekstremitet_underben: {
    name: 'Underben / fod',
    type: 'Ekstremitet',
    march: 'M',
    urgency: 'Høj',
    what: 'Typisk mange små fragmentsår, åbne frakturer og evt. amputation ved detonation tæt på jorden. Blødningen er ofte mindre end fra låret, men kan stadig være livstruende.',
    signs: ['Synlig blødning', 'Fejlstilling / instabilitet', 'Manglende evne til at støtte på benet'],
    aid: [
      'Massiv blødning: tourniquet over såret (ikke over knæleddet når det kan undgås)',
      'Mindre blødning: trykforbinding direkte på såret',
      'Stabilisér frakturer, check puls, føleevne og bevægelse distalt',
    ],
    gear: ['tourniquet', 'trykforbinding', 'splint'],
  },
  ekstremitet_arm: {
    name: 'Overarm',
    type: 'Ekstremitet',
    march: 'M',
    urgency: 'Kritisk – minutter',
    what: 'A. brachialis løber på indersiden af overarmen. Arteriel blødning herfra kan stoppes effektivt med tourniquet.',
    signs: ['Kraftig blødning', 'Kold, bleg hånd ved karskade'],
    aid: [
      'Tourniquet højt og stramt på overarmen',
      'Notér tidspunkt',
      'Mindre blødning: trykforbinding',
    ],
    gear: ['tourniquet', 'trykforbinding', 'markor'],
  },
  ekstremitet_underarm: {
    name: 'Underarm / hånd',
    type: 'Ekstremitet',
    march: 'M',
    urgency: 'Moderat',
    what: 'Hænder og underarme rammes ofte, fordi de er uden beskyttelse og ofte er løftet. Mange små sår, sene- og nerveskader. Blødningen er sjældnere livstruende.',
    signs: ['Blødning', 'Nedsat greb eller føleevne'],
    aid: [
      'Trykforbinding på blødende sår',
      'Tourniquet hvis blødningen ikke kan kontrolleres',
      'Fjern ringe/ur før hævelse',
    ],
    gear: ['trykforbinding', 'tourniquet'],
  },
  lyske: {
    name: 'Lyske / bækken',
    type: 'Junktionel',
    march: 'M',
    urgency: 'Kritisk – minutter',
    what: 'Junktionelt område: a. femoralis passerer lysken, hvor en tourniquet ikke kan lægges. Blast tæt på jorden kan også give bækkenfraktur med stor indre blødning.',
    signs: ['Kraftig blødning fra lyske eller balde', 'Smerter / instabilitet i bækkenet', 'Shocktegn uden tydelig ydre blødning'],
    aid: [
      'Direkte, hårdt tryk med det samme',
      'Pak såret tæt med hæmostatisk gaze helt ned til blødningskilden',
      'Hold tryk i mindst 3 minutter (eller iflg. produktets vejledning)',
      'Trykforbinding ovenpå pakningen',
      'Junktionel tourniquet hvis tilgængelig',
      'Mistanke om bækkenfraktur: bækkenbælte over trochanter major',
    ],
    gear: ['haemostatisk', 'trykforbinding', 'baekkenbaelte'],
  },
  aksil: {
    name: 'Armhule',
    type: 'Junktionel',
    march: 'M',
    urgency: 'Kritisk – minutter',
    what: 'Armhulen ligger i hullet mellem plader og arm og er typisk ubeskyttet. A. axillaris kan ikke afklemmes med en tourniquet.',
    signs: ['Kraftig blødning fra armhule/skulder', 'Hurtigt indsættende shock'],
    aid: [
      'Direkte tryk',
      'Pak såret med hæmostatisk gaze',
      'Hold tryk i mindst 3 minutter',
      'Trykforbinding, evt. med armen ind mod kroppen for ekstra tryk',
    ],
    gear: ['haemostatisk', 'trykforbinding'],
  },
  hals: {
    name: 'Hals',
    type: 'Junktionel',
    march: 'M',
    urgency: 'Kritisk – minutter',
    what: 'Store kar (a. carotis, v. jugularis) og luftrøret ligger overfladisk. Sår på store vener kan suge luft ind (luftemboli). Hævelse eller blod kan blokere luftvejen.',
    signs: ['Kraftig blødning', 'Hvæsende eller boblende vejrtrækning', 'Hæshed, hævelse, luft under huden'],
    aid: [
      'Direkte tryk – pak med hæmostatisk gaze',
      'Trykforbinding lagt så den ikke kvæler (fx over modsatte arm/armhule)',
      'Okklusiv forbinding (fx chest seal) ved mistanke om skade på store vener',
      'Overvåg luftvejen konstant',
    ],
    gear: ['haemostatisk', 'trykforbinding', 'chestseal'],
  },
  ansigt: {
    name: 'Ansigt',
    type: 'Hoved/ansigt',
    march: 'A',
    urgency: 'Høj',
    what: 'Fragmenter i ansigt og kæbe kan give blødning og hævelse ned i svælget og true luftvejen. Hjelmen dækker ikke ansigtet, så skaderne er hyppige.',
    signs: ['Blod i mund/svælg', 'Gurglende eller snorkende vejrtrækning', 'Personen vil sidde op og læne sig frem'],
    aid: [
      'Lad en vågen patient selv finde den stilling hvor de kan trække vejret – ofte siddende, foroverbøjet',
      'Bevidstløs: stabilt sideleje / kæbeløft, ryd munden',
      'NPA (næsekantarre) hvis uddannet – forsigtighed ved store ansigtsskader',
      'Kirurgisk luftvej kun ved uddannet personel',
    ],
    gear: ['npa', 'trykforbinding'],
  },
  oejne: {
    name: 'Øjne',
    type: 'Hoved/ansigt',
    march: 'H',
    urgency: 'Moderat (synstruende)',
    what: 'Selv meget små fragmenter kan trænge ind i øjet. Øjenskader er meget hyppige ved droner og granater. Ballistiske briller forebygger de fleste.',
    signs: ['Smerte, sløret syn', 'Synligt fremmedlegeme eller deformt øje', 'Blod i øjet'],
    aid: [
      'Rigidt øjenskjold over øjet – IKKE en trykforbinding',
      'Tryk aldrig på øjet, og fjern ikke fremmedlegemer',
      'Undlad at skylle ved mistanke om penetrerende skade',
      'Dæk evt. begge øjne for at mindske øjenbevægelser',
    ],
    gear: ['oejenskjold'],
  },
  hoved: {
    name: 'Kranie / hjerne',
    type: 'Hoved/ansigt',
    march: 'H',
    urgency: 'Høj',
    what: 'Penetrerende hovedskade eller traumatisk hjerneskade (TBI) fra fragmenter, trykbølge eller fald. Hjernen tåler meget dårligt iltmangel og lavt blodtryk – sekundær skade forebygges ved god luftvej og cirkulation.',
    signs: ['Ændret bevidsthed (AVPU)', 'Forvirring, gentagne spørgsmål', 'Ulige pupiller', 'Opkast, kramper', 'Blod eller klar væske fra næse/ører'],
    aid: [
      'Kontrollér blødning med let tryk – ikke hårdt tryk på en åben/knust kranieskade',
      'Sikr luftvej og vejrtrækning (undgå iltmangel)',
      'Hold patienten varm',
      'Overvåg og notér bevidsthedsniveau løbende',
      'Hæv overkroppen ~30° hvis muligt',
    ],
    gear: ['trykforbinding', 'hypotermi'],
  },
  thorax: {
    name: 'Brystkasse',
    type: 'Torso',
    march: 'R',
    urgency: 'Kritisk',
    what: 'Fragmenter kan perforere lungen og give pneumothorax. Luft kan blive fanget i brysthulen og trykke lunge og hjerte sammen (tension pneumothorax), som slår ihjel uden behandling. Pladerne beskytter kun det område de dækker.',
    signs: ['Tiltagende åndenød', 'Boblende/sugende sår', 'Asymmetriske brystbevægelser', 'Faldende bevidsthed, shock', 'Sent: udspilede halsvener'],
    aid: [
      'Ventileret chest seal på ALLE åbne sår – check også ryggen og armhulerne',
      'Overvåg for tension pneumothorax',
      'Ved tension: nåledekompression (kun uddannet personel)',
      'Lad den vågne patient sidde i den stilling der er lettest',
    ],
    gear: ['chestseal', 'ncd'],
  },
  abdomen: {
    name: 'Mave',
    type: 'Torso',
    march: 'C',
    urgency: 'Kritisk – kræver kirurgi',
    what: 'Fragmenter i maven kan give indre blødning fra lever, milt eller store kar. Den kan ikke stoppes med tryk i felten, så hurtig evakuering til kirurgi er afgørende. Den nederste del af maven er ofte uden for pladerne.',
    signs: ['Shocktegn uden synlig blødning', 'Spændt, øm mave', 'Tarme der ligger udenfor (evisceration)'],
    aid: [
      'Prioritér hurtig evakuering',
      'Tryk/forbinding på ydre blødning',
      'Evisceration: dæk med fugtig, ren forbinding – skub IKKE tarme ind',
      'Intet at spise eller drikke',
      'Forebyg hypotermi',
    ],
    gear: ['trykforbinding', 'hypotermi'],
  },
};

// Udstyr i førstehjælpstasken (IFAK)
export const KIT = {
  tourniquet: { name: 'Tourniquet (CAT / SOF-T)', use: 'Stopper arteriel blødning på arme og ben ved at klemme arterien helt af.' },
  trykforbinding: { name: 'Trykforbinding (Israeli bandage)', use: 'Holder pres på sår og pakning. Elastisk med trykbøjle.' },
  haemostatisk: { name: 'Hæmostatisk gaze', use: 'Pakkes ned i dybe sår, hvor tourniquet ikke kan bruges. Fremmer koagulation.' },
  chestseal: { name: 'Chest seal (ventileret)', use: 'Lukker åbne brystsår, men lader luft slippe ud for at forebygge tension.' },
  ncd: { name: 'Nål til dekompression', use: 'Aflaster tension pneumothorax. Kræver uddannelse.' },
  npa: { name: 'Næsekantarre (NPA)', use: 'Holder luftvejen åben hos en person med nedsat bevidsthed.' },
  oejenskjold: { name: 'Øjenskjold', use: 'Rigid skal over øjet uden tryk på selve øjet.' },
  hypotermi: { name: 'Hypotermitæppe', use: 'Forebygger nedkøling – en del af den dødelige triade.' },
  baekkenbaelte: { name: 'Bækkenbælte', use: 'Stabiliserer og lukker et brækket bækken for at mindske blødning.' },
  splint: { name: 'Splint (SAM)', use: 'Stabiliserer frakturer.' },
  markor: { name: 'Markør', use: 'Notér tidspunkt for tourniquet og behandling.' },
};
